apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-1
spec:
  replicas: 3
  selector:
    matchLabels:
      type: shell-box
  template:
    metadata:
      labels:
        type: shell-box
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "5000"