apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - capabilities: {}
        env:
          - name: MYSQL_PASSWORD
            value: Secret123
          - name: MYSQL_ROOT_PASSWORD
            value: Secret123
          - name: MYSQL_DATABASE
            value: example
        name: mysql
        image: mysql:5.7
        ports:
          - containerPort: 3306
            protocol: TCP
        securityContext:
          capabilities: {}
          privileged: false