apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dep-vol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tier1
  template:
    metadata:
      labels:
        app: tier1
    spec:
      containers:
      - name: test-container
        image: busybox
        command: [ "/bin/sh", "-c", "ls /etc/config/" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: app-config