apiVersion: apps/v1
kind: Deployment
metadata:
  name: box
  labels:
    app: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
      tier: tier0
  template:
    metadata:
      labels:
        app: busybox
        tier: tier0
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "10000"	