apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
      - name: webapp
        image: nginx:1.18.0
  