apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      type: box
  template:
    metadata:
      labels:
        type: box
    spec:
      containers:
      - name: box
        image: busybox
	args:
	- sleep
	- "500"