apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx
        envFrom:
          - configMapRef:
              name: loginapp-env
  replicas: 3
  selector:
    matchLabels:
      app: webapp