apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: webapp
    type: front-end
spec:
  template:
    metadata:
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3
  selector:
    matchLabels:
       type: front-end     