apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-devel
  template:
    metadata:
      labels:
        app: nodejs-devel
    spec:
      containers:
      - name: nodejs-development
        image: nodejs:current-buster     	