apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    type: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visitors
      type: db
  template:
    metadata:
      labels:
        app: visitors
        type: db
    spec:
      containers:
      - name: app-db
        image: "mysql:5.7"
        imagePullPolicy: Always
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: visitors_db
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-auth
              key: password	