apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "5000"
        envFrom:
          - configMapRef:
              name: app-config
  replicas: 2
  selector:
    matchLabels:
      app: prod