apiVersion: apps/v1
kind: Deployment
metadata:
  name: confapp
spec:
  template:
    metadata:
      labels:
        app: conf
    spec:
      containers:
      - name: confapp
        image: nginx
        envFrom:
          - configMapRef:
              name: confenv
  replicas: 3
  selector:
    matchLabels:
      app: conf