apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
   color: green
spec:
  Affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: color
              operator: In
              values:
              - green
  replicas: 2
  selector:
    matchLabels:
      color: green
  template:
    metadata:
      labels:
        color: green
    spec:
      containers:
      - name: greenapp
        image: nginx
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "green"
          effect: "NoSchedule"
