apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  lables:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
    
