apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: frontend
spec:
  containers:
  - name: box1
    image: busybox
    args:
    - sleep
    - "100000"
---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
     tier: frontend
spec:
  containers:
  - name: box2
    image: busybox
    args:
    - sleep
    - "100000"
    