apiVersion: v1
kind: Pod
metadata:
  name: nginx-mem-limit-pod
  namespace: default
spec:
  containers:
  - name: nginx-memory-pod
    image: nginx
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
