# adding cpu limits to pod
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpu-limit1
spec:
  containers:
     - name: nginx
       image: nginx
       resources:
         limits:
           cpu: "1"
         requests:
           cpu: "1"
           