apiVersion: v1
kind: Pod
metadata:
   name: web2
   labels:
     env: dev
spec:
  containers:
  - name: webapp
    image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "red"
      effect: "NoSchedule"
