apiVersion: v1
kind: Pod
metadata:
  name: nginx-cpu-limit2
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "2"
      requests:
        cpu: "1"
        