apiVersion: v1
kind: Pod
metadata:
   name: nginx-mem-limit2
   namespace: default
spec:
   containers:
   - name: nginx
     image: nginx
     resources:
       requests:
         memory: "150Mi"
       limits:
         memory: "200Mi"	       
