apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-pod1
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
      - name: redis-storage
        mountPath: /tmp/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
