apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replica-5
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx
    