apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: box-replicaset
  label:
    type: box-replica
spec:
  template:
    metadata:
      name: box-app1
      labels:
         app: box1
         tier: tier0
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "100000"
  replicas: 6
  selector:
    matchLabels:
      app: box1	