apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: a3
  labels:
    app: id3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: id3
  template:
    metadata:
      labels:
        app: id3
    spec:
       containers:
       - name: nginx
         image: nginx	 