apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: box-front
  labels:
    app: box
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: box
        image: busybox
        args:
        - sleep
        - "100000"