apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
     matchLabels:
       tier: backend
  template:
    metadata:
       labels:
          tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx