apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web1
  labels:
    env: dev
    role: web
spec:
  replicas: 4
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx	