apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replica-3
spec:
  replicas: 2
  selector:
     matchLabels:
       appType: auth
  template:
    metadata:
      labels:
        appType: auth
    spec:
      containers:
      - name: nginx
        image: nginx
