apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: a1
  labels:
    app: id1
spec:
  selector:
    matchLabels:
      app: id1
  template:
    metadata:
      labels:
        app: id1
    spec:
      containers:
      - name: busybox
        image: busybox
        args:
        - sleep
        - "100000"