apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-1
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: helloworld
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always